apiVersion: apps/v1
kind: Deployment
metadata:
  name: &service-name readinessprobe
  labels: &labels
    app: *service-name
spec:
  strategy:
    rollingUpdate:
      maxSurge: 200%        # more than the `replicas` can be used to roll out the new version
      maxUnavailable: 0 # less than the `replicas` can be available
  minReadySeconds: 1
  selector:
    matchLabels: *labels
  replicas: 1
  revisionHistoryLimit: 10
  template: 
    metadata:
      labels: *labels
    spec:
      containers:
      - name: *service-name
        image: emailtovamos/readinessprobe:v1
        command: ["./binary"]
        readinessProbe:
          httpGet:
            path: /up
            port: 10000
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1