apiVersion: v1
kind: Service
metadata:
  name: &service-name readinessprobe
spec:
  type: NodePort
  selector:
    app: *service-name
  ports:
    - name: grpc
      port: 10000
      nodePort: 30900
      protocol: TCP